const KEY='measurement-cases-v1';
const categories=['鑑界','分割合併','建物案件','法院案件'];
const today=new Date(); today.setHours(0,0,0,0);
let cases=JSON.parse(localStorage.getItem(KEY)||'[]');
const $=s=>document.querySelector(s);
const fmt=d=>d?new Intl.DateTimeFormat('zh-TW',{year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(d+'T00:00:00')):'—';
const iso=d=>d.toISOString().slice(0,10);
const diffDays=d=>Math.round((new Date(d+'T00:00:00')-today)/86400000);
const badge=c=>({鑑界:'blue',分割合併:'green',建物案件:'orange',法院案件:'red'}[c]||'blue');
function save(){localStorage.setItem(KEY,JSON.stringify(cases)); render();}
function filtered(){const q=$('#searchInput').value.trim().toLowerCase(), cat=$('#categoryFilter').value;return cases.filter(c=>(cat==='all'||c.category===cat)&&(!q||[c.name,c.caseNo,c.landNo,c.address].join(' ').toLowerCase().includes(q))).sort((a,b)=>(a.survey||'').localeCompare(b.survey||''));}
function render(){const f=filtered(), soon=cases.filter(c=>c.survey&&diffDays(c.survey)>=0&&diffDays(c.survey)<=2).length, month=cases.filter(c=>c.survey&&c.survey.slice(0,7)===iso(today).slice(0,7)).length;$('#totalStat').textContent=cases.length;$('#soonStat').textContent=soon;$('#monthStat').textContent=month;$('#categoryStat').textContent=new Set(cases.map(c=>c.category)).size;$('#listView').innerHTML=f.length?`<table class="case-table"><thead><tr><th>案件</th><th>案件分類</th><th>收件日</th><th>測量日期</th><th>案號</th><th>地號</th><th>地址</th><th>界指點數</th></tr></thead><tbody>${f.map(c=>{const soon=diffDays(c.survey)>=0&&diffDays(c.survey)<=2;return `<tr><td><div class="case-name">${esc(c.name)}</div>${c.note?`<div class="muted">${esc(c.note)}</div>`:''}</td><td><span class="badge ${badge(c.category)}">${c.category}</span></td><td>${fmt(c.received)}</td><td class="date-cell ${soon?'soon':''}">${fmt(c.survey)}${soon?'<div class="muted">◷ 即將提醒</div>':''}</td><td>${esc(c.caseNo)||'—'}</td><td>${esc(c.landNo)||'—'}</td><td>${esc(c.address)||'—'}</td><td>${c.points??'—'}</td></tr>`}).join('')}</tbody></table>`:`<div class="empty"><strong>目前沒有案件</strong><span>按右上角「新增案件」開始建立你的測量排程。</span></div>`;renderCalendar();}
function renderCalendar(){const el=$('#calendarView'), year=today.getFullYear(), month=today.getMonth(), first=new Date(year,month,1), last=new Date(year,month+1,0), start=(first.getDay()+6)%7;let html='<div class="calendar"><div class="calendar-head"><h3>'+year+' 年 '+(month+1)+' 月</h3><span class="muted">橘色標記＝兩天內測量</span></div><div class="calendar-grid">'+['一','二','三','四','五','六','日'].map(x=>`<div class="weekday">週${x}</div>`).join('');for(let i=0;i<start;i++)html+='<div class="day"></div>';for(let d=1;d<=last.getDate();d++){const date=iso(new Date(year,month,d)), list=cases.filter(c=>c.survey===date), isToday=date===iso(today);html+=`<div class="day ${isToday?'today':''}"><div class="day-number">${d}</div>${list.map(c=>`<span class="event ${diffDays(c.survey)<=2&&diffDays(c.survey)>=0?'soon':badge(c.category)}" title="${esc(c.name)}">${esc(c.name)}</span>`).join('')}</div>`}html+='</div></div>';el.innerHTML=html;}
function esc(v){return String(v||'').replace(/[&<>'"]/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[x]));}
$('#todayLabel').textContent=today.toLocaleDateString('zh-TW',{weekday:'long'});$('#todayDate').textContent=today.toLocaleDateString('zh-TW',{year:'numeric',month:'long',day:'numeric'});
$('#newCaseBtn').onclick=()=>{$('#caseForm').reset();$('#caseDialog').showModal()};$('#caseForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);cases.push({id:crypto.randomUUID(),name:f.get('name'),category:f.get('category'),received:f.get('received'),survey:f.get('survey'),caseNo:f.get('caseNo'),landNo:f.get('landNo'),address:f.get('address'),points:f.get('points')?Number(f.get('points')):null,note:f.get('note')});save();$('#caseDialog').close()};$('#searchInput').oninput=render;$('#categoryFilter').onchange=render;document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#listView').classList.toggle('hidden',b.dataset.view!=='list');$('#calendarView').classList.toggle('hidden',b.dataset.view!=='calendar')});$('#exportBtn').onclick=()=>{const header=['案件名稱','案件分類','收件日','測量日期','案號','地號','地址','界指點數','備註'];const rows=cases.map(c=>[c.name,c.category,c.received,c.survey,c.caseNo,c.landNo,c.address,c.points,c.note]);const csv='\ufeff'+[header,...rows].map(r=>r.map(x=>`"${String(x??'').replace(/"/g,'""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='測量案件時間表.csv';a.click()};render();
